(() => {
'use strict';
const API=window.CHATBOOT_API_URL||'';
const sections=['RESPUESTAS','MENUS','AVISOS','CONTACTOS','CONFIGURACION','SINONIMOS'];
const labels={RESPUESTAS:'💬 Respuestas',MENUS:'🧭 Menús',AVISOS:'📢 Avisos',CONTACTOS:'👤 Contactos',CONFIGURACION:'⚙️ Configuración',SINONIMOS:'🔎 Sinónimos'};
let token=sessionStorage.getItem('chatboot_admin_token')||'';
let data=null,current='RESPUESTAS',editing=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function get(action,params={}){const u=new URL(API);u.searchParams.set('accion',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Error de API');return j.data}
function post(payload){return fetch(API,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
function showApp(){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');buildNav();loadData() }
function showLogin(msg=''){token='';sessionStorage.removeItem('chatboot_admin_token');$('#app').classList.add('hidden');$('#login').classList.remove('hidden');$('#loginError').textContent=msg}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='Validando…';try{const out=await get('adminLogin',{hash:await sha256($('#password').value)});token=out.token;sessionStorage.setItem('chatboot_admin_token',token);$('#password').value='';showApp()}catch(err){showLogin(err.message)}});
function buildNav(){const n=$('#nav');n.innerHTML=sections.map(s=>`<button data-section="${s}">${labels[s]}</button>`).join('');n.addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(!b)return;current=b.dataset.section;editing=null;render();$('#sidebar').classList.remove('open')})}
async function loadData(){try{data=await get('adminData',{token});render()}catch(err){showLogin(err.message)}}
function render(){if(!data)return;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===current));$('#sectionTitle').textContent=labels[current].replace(/^.. /,'');const r=data.RESUMEN||{};$('#stats').innerHTML=`<div class="stat"><span>Menús</span><b>${r.menus||0}</b></div><div class="stat"><span>Respuestas</span><b>${r.respuestas||0}</b></div><div class="stat"><span>Avisos</span><b>${r.avisos||0}</b></div><div class="stat"><span>Contactos</span><b>${r.contactos||0}</b></div>`;renderTable()}
function filteredRows(){const q=$('#search').value.toLowerCase().trim();const rows=data[current]?.rows||[];return q?rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)):rows}
function renderTable(){const block=data[current]||{headers:[],rows:[]},headers=block.headers;$('#thead').innerHTML=`<tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}<th>ACCIONES</th></tr>`;$('#tbody').innerHTML=filteredRows().map((r,i)=>`<tr>${headers.map(h=>`<td class="cell-limit" title="${esc(r[h])}">${esc(r[h])}</td>`).join('')}<td class="actions"><button data-edit="${i}" title="Editar">✏️</button><button data-delete="${i}" title="Eliminar">🗑️</button></td></tr>`).join('')||`<tr><td colspan="${headers.length+1}" class="muted">No hay registros.</td></tr>`}
$('#search').addEventListener('input',renderTable);$('#refreshBtn').onclick=loadData;$('#newBtn').onclick=()=>openEditor({});$('#tbody').addEventListener('click',e=>{const rows=filteredRows();const eb=e.target.closest('[data-edit]'),db=e.target.closest('[data-delete]');if(eb)openEditor(rows[+eb.dataset.edit]);if(db)deleteRecord(rows[+db.dataset.delete])});
function openEditor(row){editing={...row};const headers=data[current].headers;$('#modalTitle').textContent=Object.keys(row).length?'Editar registro':'Nuevo registro';$('#fields').innerHTML=headers.map(h=>fieldHtml(h,row[h]||'')).join('');$('#modal').classList.remove('hidden')}
function fieldHtml(h,v){const full=['RESPUESTA','MENSAJE','PALABRAS_CLAVE','DESCRIPCION','SINONIMOS'].includes(h);if(['ACTIVO','MOSTRAR_AVISO'].includes(h))return `<div><label>${esc(h)}</label><select class="field" name="${esc(h)}"><option ${v==='SI'?'selected':''}>SI</option><option ${v==='NO'?'selected':''}>NO</option></select></div>`;if(['TIPO_RECURSO'].includes(h))return `<div><label>${h}</label><select class="field" name="${h}">${['NINGUNO','PDF','VIDEO','IMAGEN','ENLACE','WHATSAPP'].map(x=>`<option ${v===x?'selected':''}>${x}</option>`).join('')}</select></div>`;if(full)return `<div class="full"><label>${esc(h)}</label><textarea class="field" name="${esc(h)}">${esc(v)}</textarea></div>`;return `<div><label>${esc(h)}</label><input class="field" name="${esc(h)}" value="${esc(v)}"></div>`}
function closeModal(){$('#modal').classList.add('hidden');editing=null}$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;
$('#recordForm').addEventListener('submit',async e=>{e.preventDefault();const obj={};new FormData(e.target).forEach((v,k)=>obj[k]=v);try{await post({accion:'adminSave',token,hoja:current,registro:obj});closeModal();toast('Registro guardado');setTimeout(loadData,900)}catch(err){toast(err.message)}});
async function deleteRecord(row){const headers=data[current].headers,idHeader=current==='CONFIGURACION'?'CLAVE':current==='SINONIMOS'?'TERMINO':headers.find(h=>h.startsWith('ID_'));if(!idHeader||!confirm(`¿Eliminar ${row[idHeader]}?`))return;await post({accion:'adminDelete',token,hoja:current,id:row[idHeader]});toast('Registro eliminado');setTimeout(loadData,900)}
$('#logoutBtn').onclick=()=>{post({accion:'adminLogout',token});showLogin('Sesión cerrada.')};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
if(token)showApp();
})();
