const API_URL = window.CHATBOT_API_URL || '';
let nodes = window.CHATBOT_NODES || {};
let apiData = null;
const chat=document.getElementById('chat'),input=document.getElementById('questionInput'),typing=document.getElementById('typing'),crumbs=document.getElementById('breadcrumbs');
let current='main',history=[],path=[];
const sessionId = localStorage.getItem('chatboot_session') || (crypto.randomUUID ? crypto.randomUUID() : Date.now()+'-'+Math.random());
localStorage.setItem('chatboot_session',sessionId);
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ ]/g,' ');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=()=>new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});
const scroll=()=>setTimeout(()=>chat.scrollTop=chat.scrollHeight,30);
function bubble(html,who='bot'){const d=document.createElement('div');d.className='bubble '+who;d.innerHTML=html+`<div class="time">${time()}</div>`;chat.appendChild(d);scroll();return d}
function user(t){bubble(esc(t),'me')}
function renderCrumbs(){crumbs.textContent=path.length?'Inicio › '+path.map(x=>x.label).join(' › '):'Inicio'}
function showTyping(cb){typing.classList.remove('hidden');scroll();setTimeout(()=>{typing.classList.add('hidden');cb()},420)}
function openViewer(url){document.getElementById('viewer').classList.remove('hidden');document.getElementById('viewerFrame').src=url}
document.getElementById('closeViewer').onclick=()=>{document.getElementById('viewer').classList.add('hidden');document.getElementById('viewerFrame').src=''};
function attachmentFromResponse(r){const type=String(r.TIPO_RECURSO||'').toUpperCase(),url=r.URL_RECURSO||'',title=r.TEXTO_BOTON||'Abrir recurso';if(!type||type==='NINGUNO')return[];if(type==='PDF'||type==='ENLACE')return[{type:'link',url,title}];if(type==='VIDEO')return[{type:'video',url,title}];if(type==='IMAGEN')return[{type:'image',url,link:url,title}];if(type==='WHATSAPP'){const phone=(apiData?.configuracion?.WHATSAPP_PRINCIPAL||'529372547287').replace(/\D/g,'');const msg=`Hola, necesito apoyo del área de Recaudación.\n\nConsulta: ${r.PREGUNTA||''}\nVengo del Asistente Abordo.`;return[{type:'link',url:`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,title:title||'Abrir WhatsApp'}]}return[]}
function buildNodes(data){const out={};const menus=data.menus||[],answers=data.respuestas||[];const cfg=data.configuracion||{};const children={};menus.forEach(m=>{const p=m.ID_PADRE||'__root';(children[p]||(children[p]=[])).push(m)});Object.values(children).forEach(a=>a.sort((x,y)=>(+x.ORDEN||999)-(+y.ORDEN||999)));
 const answerByMenu={};answers.forEach(r=>(answerByMenu[r.ID_MENU]||(answerByMenu[r.ID_MENU]=[])).push(r));Object.values(answerByMenu).forEach(a=>a.sort((x,y)=>(+x.ORDEN||999)-(+y.ORDEN||999)));
 out.main={type:'question',prompt:cfg.MENSAJE_BIENVENIDA||'Hola, soy Asistente Abordo. ¿En qué puedo ayudarte?',options:(children.__root||[]).map(m=>({label:`${m.ICONO||''} ${m.TITULO}`.trim(),next:'menu_'+m.ID_MENU}))};
 menus.forEach(m=>{const opts=[];(children[m.ID_MENU]||[]).forEach(c=>opts.push({label:`${c.ICONO||''} ${c.TITULO}`.trim(),next:'menu_'+c.ID_MENU}));(answerByMenu[m.ID_MENU]||[]).forEach(r=>{const id='resp_'+r.ID_RESPUESTA;opts.push({label:r.PREGUNTA,next:id});out[id]={type:'message',idRespuesta:r.ID_RESPUESTA,text:r.RESPUESTA||'',keywords:r.PALABRAS_CLAVE||'',showNotice:String(r.MOSTRAR_AVISO||'').toUpperCase()==='SI',attachments:attachmentFromResponse(r)};});opts.push({label:'← REGRESAR',action:'back'});out['menu_'+m.ID_MENU]={type:'question',prompt:m.TITULO,keywords:m.PALABRAS_CLAVE||'',options:opts};});
 if(!out.main.options.length)return null;return out}
function attachments(node,box){if(!node.attachments?.length)return;const a=document.createElement('div');a.className='actions';node.attachments.forEach(att=>{if(att.type==='image'){const link=document.createElement('a');link.href=att.link||att.url;link.target='_blank';link.rel='noopener noreferrer';const img=document.createElement('img');img.src=att.url;img.className='attachment-img';img.alt=att.title||'Abrir recurso';link.appendChild(img);a.appendChild(link)}else{const b=document.createElement('button');b.textContent=att.type==='video'?'▶ '+(att.title||'Ver video'):(att.title||'Abrir recurso');b.onclick=()=>{track(att.type==='video'?'ABRIR_VIDEO':'ABRIR_RECURSO',{idRespuesta:node.idRespuesta});if(att.type==='video'||String(att.url).toLowerCase().includes('.pdf'))openViewer(att.url);else window.open(att.url,'_blank','noopener,noreferrer')};a.appendChild(b)}});box.appendChild(a)}
function feedback(box,node){if(!node.idRespuesta)return;const d=document.createElement('div');d.className='feedback';d.innerHTML='¿Te sirvió esta respuesta? <button>👍 Sí</button><button>👎 No</button>';const bs=d.querySelectorAll('button');bs[0].onclick=()=>{d.textContent='Gracias por tu opinión.';rating(node.idRespuesta,'POSITIVA','')};bs[1].onclick=()=>{const comment=prompt('¿Qué información te hizo falta? (opcional)')||'';d.textContent='Gracias. Revisaremos esta respuesta.';rating(node.idRespuesta,'NEGATIVA',comment)};box.appendChild(d)}
function present(id,add=true,label=''){const n=nodes[id];if(!n)return bubble('No pude localizar esa información.');if(add&&current){history.push({id:current,path:[...path]});if(label)path.push({id,label})}current=id;renderCrumbs();showTyping(()=>{if(n.type==='question'){bubble('<strong>'+esc(n.prompt)+'</strong>');const opts=document.createElement('div');opts.className='options';n.options.forEach(o=>{const b=document.createElement('button');b.className='option-btn';b.textContent=o.label;b.onclick=()=>{user(o.label);if(o.action==='back'||/REGRESAR/i.test(o.label))back();else present(o.next,true,o.label)};opts.appendChild(b)});chat.appendChild(opts)}else{let html='<div>'+esc(n.text).replace(/\n/g,'<br>')+'</div>';if(n.showNotice&&apiData?.configuracion?.AVISO_LEGAL)html+=`<div class="notice">${esc(apiData.configuracion.AVISO_LEGAL)}</div>`;const box=bubble(html);attachments(n,box);feedback(box,n);const opts=document.createElement('div');opts.className='options';const b=document.createElement('button');b.className='option-btn';b.textContent='← Regresar';b.onclick=back;opts.appendChild(b);chat.appendChild(opts)}track('VER_CONTENIDO',{idRespuesta:n.idRespuesta||'',resultado:id});scroll()})}
function back(){if(!history.length)return home();const h=history.pop();current=h.id;path=h.path;renderCrumbs();present(current,false)}
function home(){chat.innerHTML='';history=[];path=[];current='main';renderCrumbs();showNotices();present('main',false)}
function showNotices(){(apiData?.avisos||[]).forEach(a=>bubble(`<strong>📢 ${esc(a.TITULO||'Aviso')}</strong><br>${esc(a.MENSAJE||'')}`))}
function score(q,n){const hay=norm([n.prompt,n.text,n.keywords,...(n.options||[]).map(o=>o.label)].join(' '));return norm(q).split(/\s+/).filter(w=>w.length>2).reduce((s,w)=>s+(hay.includes(w)?1:0),0)}
function search(q){const nq=norm(q);if(!nq)return;if(/inicio|menu principal/.test(nq))return home();if(/regresar|volver|atras/.test(nq))return back();const direct=Object.entries(nodes).map(([id,n])=>({id,n,s:score(q,n)})).sort((a,b)=>b.s-a.s);if(!direct[0]||direct[0].s<1){bubble('No encontré una coincidencia clara. Intenta con otras palabras o selecciona una categoría.');track('SIN_RESULTADOS',{busqueda:q,resultado:'SIN_RESULTADOS'});return}const r=direct[0];bubble(`Encontré información relacionada con <strong>${esc(q)}</strong>.`);track('BUSCAR',{busqueda:q,resultado:r.id});present(r.id,true,r.n.prompt||r.n.text?.slice(0,35)||'Resultado')}
function send(){const q=input.value.trim();if(!q)return;user(q);input.value='';search(q)}
document.getElementById('sendBtn').onclick=send;input.addEventListener('keydown',e=>{if(e.key==='Enter')send()});document.getElementById('homeBtn').onclick=home;document.getElementById('backBtn').onclick=back;
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(SR){rec=new SR();rec.lang='es-MX';rec.onresult=e=>{input.value=e.results[0][0].transcript;track('USAR_VOZ',{});send()};rec.onerror=()=>bubble('No pude escuchar con claridad. También puedes escribir tu pregunta.')}else document.getElementById('micBtn').disabled=true;document.getElementById('micBtn').onclick=()=>rec&&rec.start();
async function post(payload){if(!API_URL)return;try{await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),mode:'no-cors'})}catch(e){console.warn('No se pudo registrar',e)}}
function track(evento,extra={}){try{const x=JSON.parse(localStorage.getItem('chatboot_stats')||'{}');x[evento]=(x[evento]||0)+1;localStorage.setItem('chatboot_stats',JSON.stringify(x))}catch(e){}post({accion:'estadistica',sesion:sessionId,evento,idMenu:current,idRespuesta:extra.idRespuesta||'',busqueda:extra.busqueda||'',resultado:extra.resultado||'',dispositivo:navigator.platform||'',navegador:navigator.userAgent||''})}
function rating(idRespuesta,valoracion,comentario){post({accion:'valoracion',sesion:sessionId,idRespuesta,valoracion,comentario})}
async function loadApi(){if(!API_URL)return false;try{const res=await fetch(API_URL+'?accion=datos&_='+Date.now());if(!res.ok)throw new Error('HTTP '+res.status);const json=await res.json();if(!json.ok)throw new Error(json.error||'API sin respuesta');apiData=json.data;const dynamic=buildNodes(apiData);if(dynamic)nodes=dynamic;const cfg=apiData.configuracion||{};if(cfg.NOMBRE_CHATBOT)document.querySelector('.brand h1').textContent=cfg.NOMBRE_CHATBOT;if(cfg.SUBTITULO)document.querySelector('.brand p').textContent=cfg.SUBTITULO+' · En línea';if(cfg.COLOR_PRINCIPAL)document.documentElement.style.setProperty('--accent',cfg.COLOR_PRINCIPAL);return true}catch(e){console.warn('Se usará contenido local:',e);bubble('⚠️ No fue posible actualizar desde Google Sheets. Se muestra el contenido local disponible.');return false}}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.getElementById('installBtn').classList.remove('hidden')});document.getElementById('installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};
(async()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');await loadApi();track('INICIO',{});home()})();
